Card moves 12/2/21
OpenFabrics/fsdp_docs pull request #87
Opened 2021-12-02 21:17 UTC by JSpewock

*moved Mellanox 653106A 200G 2-port VPI from port 3 on node-07 to port 3
on node-05
*moved Mellanox 653106A 200G 2-port VPI from port 3 on node-08 to port 3
on node-06

resolves #86 

Signed-off-by: Jeremy Spewock <jspewock@iol.unh.edu>

2021-12-02 21:33 UTC, dledford requested changes
Need to move the lines from both port 1 and port 2 from nodes 07/08 to 05/06

2021-12-03 13:44 UTC, lylavoie commented
Need to update ib_fabric.md document, to list the correct connections.  An not tracked in this "code" but we also need to update the descriptions on the switch port configuration on the Mellanox switch (I can show you how to do that).

2021-12-03 13:47 UTC, lylavoie requested changes
Need to update ib_fabric.md and ethernet_fabrics.md documents, to list the correct connections. An not tracked in this "code" but we also need to update the descriptions on the switch port configuration on the Mellanox and Sonic switches (I can show you how to do that).

2021-12-03 19:28 UTC, dledford approved these changes
Looks like this addresses both prior review comments

2021-12-03 20:45 UTC, merged